name: Test and Build Go App
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go version
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
        id: go
      - name: Get the latest dependencies
        run: go get -v
      - name: Run the go app
        run: go run main.go -search="example.example"
      - name: Build the go app
        run: go build .
      - name: Run the go app build
        run: ./network-database -search="example.example"
